#This file handles the expected answers for the test cases

expected_answer1 = []

expected_answer2 = []

expected_answer3 = [{'name': 'Alex Rasmussen',
'creation_time': '2015-09-21T03:35:28',
'text': 'RT @mikeash: Joe’s code has 20 bugs. If Joe fixes 2 bugs per hour for 8 hours, how many bugs does Joe’s code have now?  Answer: 27.'},
{'name': 'Alex Rasmussen',
'creation_time': '2015-09-21T03:04:19',
'text': '@b0rk Just found this; might prove useful: https://t.co/6esJERk2QI'},
{'name': 'Alex Feinberg',
'creation_time': '2015-09-21T03:02:31',
'text': '@__oana did he finally touch a poop for $20?'},
{'name': 'Alex Feinberg',
'creation_time': '2015-09-21T03:01:50',
'text': 'RT @adapteva: Wow, this is a huge premium! Long and persistent investment in avr paid off. #arduino #avrfreaks  https://t.co/W5m8SXO9Uw'}]

expected_answer4 = [{'name': 'ISTC for Big Data',
'creation_time': '2015-09-19T21:05:10',
'text': 'RT @srchvrs: Big data is a myth say Andrew Crotty and colleagues at #vldb2015 http://t.co/Vj5IypD8Jb http://t.co/i54tV7Xsqy'},
{'name': 'ISTC for Big Data',
'creation_time': '2015-09-18T21:05:40',
'text': '#FF @IEEE_HPEC Congrats on a great 2015 conference on the intersection of Big Data and #HPC. See you next year.'}]

expected_answer5 = [{'name': 'OC Arch+Design',
'creation_time': '2015-09-17T22:07:33',
'text': '@Beakerhead Sooo excited for #beakernight http://t.co/7Y4hS6guUE'},
{'name': 'OC Arch+Design',
'creation_time': '2015-09-17T01:57:51',
'text': 'RT @Beakerhead: Chemistry! Mixology! Devilish eggs and whiskey sour by @TheBeltliner for #EngineeredEats 2015! #YYC #YYCfood http://t.co/dE…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-09-17T00:21:38',
'text': '@Beakerhead the giant bunnies have landed in Central Memorial Park in #Beltline http://t.co/V3yeMHPhld'},
{'name': 'OC Arch+Design',
'creation_time': '2015-09-15T01:43:59',
'text': 'RT @FastCompany: The 2015 Innovation By Design Awards Winners: Social Good: http://t.co/PQg857sc5H #BestDesignFC http://t.co/7iJ6zP6Zsa'},
{'name': 'OC Arch+Design',
'creation_time': '2015-09-15T01:43:32',
'text': 'RT @mybowness: Connect and share your ideas on how to build a flood resilient community by attending the Livable Cities Forum’s... http://t…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-09-15T01:42:04',
'text': "RT @Beakerhead: A little rain won't stop construction of Station B @fortcalgary! This is going to be awesome. #yyc http://t.co/clTwb5coc4"},
{'name': 'OC Arch+Design',
'creation_time': '2015-09-15T01:42:00',
'text': "RT @Beakerhead: 8 things to see and do at @Beakerhead '15: http://t.co/EXZRNsDAZM via @HuffingtonPost http://t.co/D8DDbIoCB5"},
{'name': 'OC Arch+Design',
'creation_time': '2015-09-15T01:10:13',
'text': '@NewUrbanYYC @InHouseSociety Calgary developer builds condos that require no down payment /via @globeandmail http://t.co/8P35ZixAHc'},
{'name': 'OC Arch+Design',
'creation_time': '2015-09-13T07:57:43',
'text': '@_BassBus_  wicked! @villagebrewery summer not dead yet! http://t.co/MQqKX9UuFA'},
{'name': 'OC Arch+Design',
'creation_time': '2015-09-13T06:27:37',
'text': "RT @JustinTrudeau: It's unfair for teachers to pay out-of-pocket to improve their classroom environment. Sign if you agree. https://t.co/o4…"},
{'name': 'OC Arch+Design',
'creation_time': '2015-09-13T06:26:38',
'text': 'RT @Rockster: Hey look! @midtownyyc is promoting #BeerWeek! @AltaBrewers see event list here: albertabrewers.ca'},
{'name': 'OC Arch+Design',
'creation_time': '2015-09-13T06:26:27',
'text': 'RT @FemmesFataleYYC: Aged #agave spirits &amp; antojitos w/ @labonitafunk @NativeTongueYYC!   Ladies RSVP online http://t.co/vRgjOD8WDG http://…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-09-13T06:26:12',
'text': 'RT @woolie: Want to subdivide and max out lot coverage with four story houses? Awesome! Go for it! https://t.co/0cVoJk3REr http://t.co/MDqa…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-09-13T05:04:07',
'text': 'Loving this #yyccircle da wagons!steampunk goddess dances on top of  bassbus.pumphouse park...@villagebrewery is here http://t.co/osHMBpybIo'},
{'name': 'OC Arch+Design',
'creation_time': '2015-09-08T07:02:29',
'text': 'RT @FastCompany: 6 inventions that will turn your breakfast into a Pee-Wee Herman fever dream: http://t.co/9PiZxNyKLn http://t.co/bt5npmtbxj'},
{'name': 'OC Arch+Design',
'creation_time': '2015-08-09T01:01:38',
'text': 'RT @DruhFarrell: Calgary next please. "@yycfhw: Coming Soon to America: One Fare Card for All Transit http://t.co/ZdZzlAXyQ8 #transit"'},
{'name': 'OC Arch+Design',
'creation_time': '2015-08-09T01:01:30',
'text': 'RT @tastecalgary: Brunch is happening now! Come and get it. #DuckAndWaffles'},
{'name': 'OC Arch+Design',
'creation_time': '2015-08-06T08:22:31',
'text': "RT @LaraPresber: Just updated our #press with our most recent #feature in The Globe and Mail, check it out if you haven't already!... http:…"},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-31T03:19:03',
'text': 'RT @pigeonholeyyc: Patio is open at 4pm today so you can enjoy this heat and a cocktail or two! #earlgreymartinis 🍸'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-31T00:43:00',
'text': 'RT @beltline_plan: @beltline_pres @AvenueMagazine #beltline is best YYC Neighbourhood 2015 http://t.co/RvJDe9zrrK'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-24T06:21:35',
'text': 'RT @NickKristof: As Obama departs for Africa, people in South Sudan are collapsing from hunger. My column: http://t.co/aIE97xmmcA http://t.…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-24T06:18:29',
'text': 'RT @proofyyc: Come join us and @Container_Bar and put some tiki drinks in your booze locker. Photo from @itsmarieclare http://t.co/CkprFRBU…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-24T06:17:19',
'text': 'RT @tastecalgary: Amazing news, @milktigerlounge. Well deserved - huuuuge congrats! I love our hood. @proofyyc https://t.co/xQ3X7vwrku'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-24T06:17:09',
'text': "RT @proofyyc: We're linking up with our friends @Container_Bar Sunday for a Tikilicious takeover! @bigfkahuna will be holding court http://…"},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-18T21:00:19',
'text': 'RT @joshyyc: The Really Big One - remind me NOT to retire on the west coast. This is truly terrifying http://t.co/XwKrFU4nEV'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-18T20:37:27',
'text': 'RT @joshyyc: Would make a great t-shirt https://t.co/BLUPxRkapi'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-18T20:36:11',
'text': "RT @WIRED: Fly over Pluto's icy mountains in this amazing simulated video http://t.co/HejBnHmvyd"},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-18T20:35:59',
'text': 'RT @FastCompany: Tired of your cubicle? Work from the woods: http://t.co/Ivy1SORMgv http://t.co/7seQkpHqhD'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-18T08:26:33',
'text': '@proofyyc @BigRockBrewery @lastbestbrew love the new Beer-verage! http://t.co/SXLEwWxZen'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-15T04:35:03',
'text': 'RT @AutomatedAlice: Our special requests @proofyyc! As delicious as all of their original drinks. #mintjulep #manhattan @cdngrrl http://t.c…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-15T04:34:54',
'text': 'RT @Avecbistro: Gin, whiskey and scotch flights... @cowtownwine thank you for the pain @CulinaireMag #ABbevawards2015'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-14T20:34:20',
'text': 'RT @beltline_pres: . alternative futures for Ward 8 . which is better for urban Calgary?  #Beltline @EWoolleyWard8 http://t.co/VjTLG9De03'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-14T20:34:07',
'text': 'RT @JonesingforKate: Congrats to the amazing @GerardoYYC for receiving a #bikeawards for all his work in the cycling community #yycbike htt…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-11T10:54:53',
'text': '@NativeTongueYYC diner with the in laws...never better! Glad you are part of the hood! http://t.co/9DL96nHIRi'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-11T09:41:52',
'text': 'RT @DiscoverMag: How New Horizons survived the 40-year-glitch and made it to Pluto: http://t.co/HrkpA3a8oG http://t.co/2BolZvdL5Z'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-11T09:41:04',
'text': 'RT @calgaryherald: .@DonBraid: On royalties, NDP should slow down and industry should calm down http://t.co/p098QdG5CN #ableg'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-11T09:40:44',
'text': 'RT @SunshineVillage: The towers are in! (#TeepeeTown2.0) http://t.co/xkccWulcgj'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-09T23:53:14',
'text': 'RT @MealshareTeam: So many great trucks out today for #PicnicInThePark! Get down here and soak up the sun with great music &amp; eats! http://t…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-09T23:53:08',
'text': 'RT @DruhFarrell: Excellent article! "@joshyyc: How to stop the carnage on our streets  http://t.co/Wu5onDiUed #yyccc"'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-09T23:52:11',
'text': 'RT @TomBabin: Five events to check out at @Cyclepalooza  http://t.co/eUkVGR7Rkm #yycbike http://t.co/0s6HVFTqlw'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-09T23:51:40',
'text': "RT @yycfoodtrucks: Can't beat $6 bottles of @villagebrewery with some amazing local music by @_BassBus_! See you all tomorrow from 11-8! ht…"},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-09T23:51:27',
'text': 'RT @lrojek: rodeo fun with @chimaincalgary #Stampede2015 http://t.co/OtUUo4c6cS'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-09T23:51:23',
'text': 'RT @beltlineYYC: more rodeo fun with @beltline_pres @joececiyyc #Stampede2015 http://t.co/fA2bjhOqic'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-09T23:51:13',
'text': 'RT @JonesingforKate: So proud of @GerardoYYC and Signe doing a great job talking about @Cyclepalooza ! Yeah Bike Prom! #yycbike http://t.co…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-09T05:44:07',
'text': 'RT @NativeTongueYYC: Our tortillas are handmade from scratch every day, using non-GMO, landrace corn from @masiendanyc .… https://t.co/Voft…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-09T05:43:58',
'text': 'RT @yycfoodtrucks: Skip the grounds and come picnic with us in @vicparkbrz today! Did we mention the cold @villagebrewery beers? 😉🍻 http://…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-09T05:43:52',
'text': 'RT @vicparkbrz: We have a photo booth set up at #PicnicInThePark! Stop by and snap a pic with us #vicparkyyc #yyc @yycfoodtrucks http://t.c…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-09T05:43:44',
'text': 'RT @LaraPresber: Another happy cyclist! Nice to meet you @micropainter and enjoy!! #CalgaryCycleChic #YYCbike http://t.co/jI4aR55Khs'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-08T10:35:30',
'text': 'RT @yycfoodtrucks: Our FoodTruck lineup has been announced! Head over to our Facebook Event page to check it out https://t.co/dokywnVTpj ht…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-07-08T10:35:25',
'text': 'RT @yycfoodtrucks: See you all tomorrow!! 🍴☀️🍻 #PicnicInThePark @vicparkbrz http://t.co/f9Zpd62e4o'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-26T01:35:01',
'text': 'RT @yycfoodtrucks: Still looking for a few volunteers this weekend! Must love food trucks, beer and sunshine! http://t.co/ZUcH1yfsBS! http:…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-26T01:34:42',
'text': "RT @DaleCalkins: Touring @UCalgaryEVDS' Aging In Place Laneway House. Fantastic project! https://t.co/6OiEg0A5VF #yycplan @DruhFarrell http…"},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-26T01:33:40',
'text': 'RT @LedgeWatcher: Carbon rate in Alberta will increase. Minister says "Alberta is getting serious" about climate change. #ableg #cbc http:/…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-26T01:31:48',
'text': 'RT @DaleCalkins: Quick selection of those "very seldom at capacity" racks on Stephen Av. We can do better. #yycbike @downtowncalgary http:/…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-26T01:30:38',
'text': 'RT @AvenueMagazine: 7 new things in Banff this summer including spas, spirits and stand-up paddleboarding. http://t.co/KMmzfNg7XV'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-26T01:30:28',
'text': 'RT @LaraPresber: Come visit is @ourparkonline #PARKSHOP #popup @chinookcentre right now!!!! We will be here until #Saturday then... http://…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-26T01:30:11',
'text': 'RT @ourPARKonline: @LaraPresber @LaurenBagliore @espyexperience @LLMLEATHER all set up at #PARKSHOP today http://t.co/wmyibl8SFH'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-26T01:30:04',
'text': 'RT @Brangwyn: @CalgaryGeorge @WBrettWilson @cmfrc @TourismCalgary  Photos from Breakfast on the Bridge #yyc https://t.co/uJxHBRIh9r http://…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-25T01:30:20',
'text': 'RT @DruhFarrell: Thanks @EWoolleyWard8 and the Ward 8 Team for putting on a great party for the Cycle Track Launch! #yycbike'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-25T01:30:02',
'text': 'RT @JonesingforKate: Our pic is out! Funny looking bike ☺️ @ArushaCentre @bikecalgary @Cyclepalooza @OpenStreetsYYC @beltline_pres http://t…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-25T01:29:34',
'text': "RT @beltline_plan: Don't miss @vicparkbrz Park Sale Central Memorial Park in #Beltline this Sunday!"},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-25T01:25:04',
'text': "RT @vicparkbrz: We're partnering up with @tastecalgary to bring you some delicious picnic baskets for #PARKSALE2015 http://t.co/idS6RZYs3X"},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-25T01:24:47',
'text': 'RT @dan_northfield: Wednesday @TheDrumCalgary @sledisland w/ @TheBackhomes and friends! @BigRockBrewery http://t.co/APe8hbKxc3'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-20T03:59:48',
'text': 'RT @JonesingforKate: The best part about the #cycletrack ? Bumping into friends, chatting, smiling, high fiving all on my way to work! @Tom…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-20T03:59:19',
'text': '@mikesbloggity @calgarybybike why the paper? why not an app or mobile device website?'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-20T03:29:11',
'text': 'RT @cderworiz: Plan to expand Lake Louise ski hill sparks debate over environmental impact http://t.co/lIubZA0dgj #lakelouise #ski #parksca…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-19T22:03:09',
'text': 'RT @dinnerwithjulie: On my way to the neighbour day Eve party on the lawn @CBCEyeopener w fresh pastries from @ManuelLatruwe http://t.co/D5…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-19T22:03:04',
'text': 'RT @beltline_plan: @dinnerwithjulie @beltline_foodie @CBCEyeopener  #Beltline Victoria residents love @ManuelLatruwe'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-19T05:33:47',
'text': 'RT @WIRED: Twitter is killing Twitter to save Twitter http://t.co/yUr6quk63s'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-11T10:29:55',
'text': 'RT @MarissaToohey: Way to go @beltline_pres! Your #yycawards community advocate award is so well deserved'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-11T10:29:48',
'text': 'RT @beltline_plan: @beltline_trans @Beltline_Parks @Beltline_SocEnv @beltlineYYC @beltline_pres congrats on #yycaward ! Your tenacious dedi…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-11T09:35:03',
'text': '@NewUrbanYYC @InHouseSociety congratulations on you #yycaward !well deserved!'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-07T09:38:10',
'text': 'RT @beltline_plan: @beltline_pres @CalgFoundation @CalgaryParks @ParksFdnCalgary pls RT peeps needed to fill da boxes Sun 8 till done http:…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-07T09:38:07',
'text': 'RT @Beltline_SocEnv: There will be 2 community gardens up and running this summer in #Beltline thanks to amazing community work! @cityofcal…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-07T09:37:48',
'text': 'RT @LaraPresber: Looking for something fun to do Sunday? The #beltline community garden needs more volunteers starting 8am http://t.co/kWan…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-07T03:26:03',
'text': 'RT @beltline_plan: @CalgFoundation @ParksFdnCalgary @CalgaryParks #Beltline drill team hard at work in Haultain Park today http://t.co/5dif…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-07T03:25:35',
'text': 'RT @beltline_plan: Prep work is started!great morning! Come on over &amp; lend a hand http://t.co/9aXY5BjJsJ'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-07T03:25:32',
'text': 'RT @beltline_pres: . support #yyc cycle tracks . tell city hall .  #Beltline loves bikes . sign here .  https://t.co/4XfAsibVnW http://t.co…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-05T04:25:54',
'text': 'RT @LaraPresber: Getting ready for our #skirts to go to #PARKSHOW 2015 #popup #shop in @chinookcentre put on by @ourparkonline!... http://t…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-05T04:25:01',
'text': 'RT @FastCompany: These are the giant corporations that own your favorite organic brands  http://t.co/9yMW5wSWl0 http://t.co/ZwKcCtdGOU'},
{'name': 'OC Arch+Design',
'creation_time': '2015-06-05T04:24:52',
'text': 'RT @beltline_plan: Gonna have great weather for #beltline Victoria Centre Community garden build Sat! Come help out and grow some veg! http…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-05-26T05:36:29',
'text': 'RT @WIRED: The next Roomba may recognize all your crap http://t.co/H2EWxPMA3p'},
{'name': 'OC Arch+Design',
'creation_time': '2015-05-26T01:01:43',
'text': 'RT @yyctransport: Check out the new cycle tracks education page! Tips for walking, driving &amp; biking in/around the new tracks http://t.co/Iy…'},
{'name': 'OC Arch+Design',
'creation_time': '2015-05-26T01:00:19',
'text': 'RT @Gothamist: Looking for a spot to hang today? Here’s our list of NYC’s 15 best bars with backyards http://t.co/G3x13VIr3s http://t.co/vc…'},
{'name': 'OC Arch+Design',
'creation_time': '2014-11-26T21:07:22',
'text': 'RT @fusiliyyc: @OC_AD @beltline_plan if you put organics or recyclables in the trash in Sweden, you get fined. They also import garbage fro…'},
{'name': 'OC Arch+Design',
'creation_time': '2014-11-26T21:00:15',
'text': 'RT @beltline_plan: @BradJLamb bringing urban food, real orchard &amp; unique new public open space to #beltline. http://t.co/J9MlCmSPQO'},
{'name': 'OC Arch+Design',
'creation_time': '2014-11-26T20:59:55',
'text': 'RT @beltline_plan: Pattison to bolt billboard on Eastern Block in #beltline 1 block &amp; visible from +/-500 households (New Era &amp; Alura) http…'},
{'name': 'OC Arch+Design',
'creation_time': '2014-11-24T22:25:56',
'text': "Less Than 1% Of Sweden's Trash Ends Up In Landfills | IFLScience http://t.co/M1wDSPEZ5e"},
{'name': 'OC Arch+Design',
'creation_time': '2014-11-07T05:55:13',
'text': "RT @tastecalgary: Patio signage up! Your friends can now find you when you meet them for dinner here. If they still can't, friends off. htt…"},
{'name': 'OC Arch+Design',
'creation_time': '2014-11-07T02:40:22',
'text': "RT @beltline_plan: 1 St SW underpass in #beltline &amp; @vicparkbrz.construction early 2015.complete prior to Stampede.now let's do 8 St SW.@EW…"},
{'name': 'OC Arch+Design',
'creation_time': '2014-10-22T21:25:19',
'text': 'RT @beltline_plan: @NewUrbanYYC @CBCEyeopener Fantastic news for saving historic Enoch Sales House in #beltline &amp; @vicparkbrz .Now up to #y…'},
{'name': 'OC Arch+Design',
'creation_time': '2014-10-02T22:39:19',
'text': 'RT @TallboyStudio: Our new window &amp; sign on 1 St in #beltline &amp; @vicparkbrz http://t.co/9biL7YXWiW'},
{'name': 'OC Arch+Design',
'creation_time': '2014-09-24T03:42:50',
'text': 'RT @LaraPresber: This could be fun @TallboyStudio Colorful Beer Branding http://t.co/kyZTnaMDEN #ArtDesign http://t.co/WkY8ZpDRav'},
{'name': 'OC Arch+Design',
'creation_time': '2014-09-12T23:03:36',
'text': 'RT @TallboyStudio: Not sure how we feel about the #snow in #calgary today #winteriscoming http://t.co/l4xQUpMNdt'},
{'name': 'OC Arch+Design',
'creation_time': '2014-09-12T23:03:18',
'text': 'RT @TallboyStudio: #Foil #dress on the fly @LaraPresber @Beakerhead almost #show #time #fashion #Beakerhead2014 #hudsonbay #fashionshow htt…'},
{'name': 'OC Arch+Design',
'creation_time': '2013-09-29T06:01:26',
'text': "@enmax @HillhurstSunny @DruhFarrell These electrical boxes must be moved...what a shame! I can't stand 'em any longer http://t.co/CRHhWGIQ1N"},
{'name': 'OC Arch+Design',
'creation_time': '2013-09-29T05:56:49',
'text': 'Only in #yyc do we spend millions on fantastic plaza and do nothing about ridiculous electrical boxes.what a shame! http://t.co/5qGYote5Vl'},
{'name': 'OC Arch+Design',
'creation_time': '2013-09-27T03:41:06',
'text': 'RT @beltline_plan: @CBCCalgary #beltline @HillhurstSunny @CBM_CA flooding focus on rural communities w 0 economic output.real issue future …'},
{'name': 'OC Arch+Design',
'creation_time': '2013-09-27T03:40:44',
'text': 'RT @beltline_plan: @CBCCalgary #beltline@CBM_CA @HillhurstSunny all for helping neighbours BUT 75K people affected in Calgary with $BILLION…'}]